image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build
    command: >
      git clone https://github.com/emscripten-core/emsdk.git;
      cd emsdk && ./emsdk install 2.0.4 && ./emsdk activate 2.0.4;
      source emsdk_env.sh;